export {
  FIRST_SENTENCE,
  PARAGRAPH_COUNT_DEFAULT,
  PARAGRAPH_COUNT_MAX,
  PARAGRAPH_COUNT_MIN,
  SENTENCE_RANGE_DEFAULT,
  SENTENCE_RANGE_MAX,
  SENTENCE_RANGE_MIN,
  WORD_RANGE_DEFAULT,
  WORD_RANGE_MAX,
  WORD_RANGE_MIN,
  clampParagraphCount,
  clampRangeBound,
  generateLoremIpsum,
  normalizeInclusiveRange,
  randFromArray,
  randIntFromInterval,
  type GenerateLoremIpsumOptions,
} from "./loremIpsumGenerator.service";
