export {
  TEMPERATURE_SCALES,
  convertCelsiusToKelvin,
  convertDelisleToKelvin,
  convertFahrenheitToKelvin,
  convertFromScale,
  convertKelvinToCelsius,
  convertKelvinToDelisle,
  convertKelvinToFahrenheit,
  convertKelvinToNewton,
  convertKelvinToRankine,
  convertKelvinToReaumur,
  convertKelvinToRomer,
  convertNewtonToKelvin,
  convertRankineToKelvin,
  convertReaumurToKelvin,
  convertRomerToKelvin,
  initialTemperatures,
  parseTemperatureInput,
  roundTemperature,
  type TemperatureScale,
  type TemperatureScaleMeta,
} from "./temperatureConverter.service";
