export {
  ASCII_FONTS,
  DEFAULT_FONT,
  DEFAULT_INPUT,
  DEFAULT_WIDTH,
  FIGLET_FONT_PATH,
  WIDTH_MAX,
  WIDTH_MIN,
  clampWidth,
  configureBrowserFigletFonts,
  normalizeFont,
  renderAsciiText,
  tryRenderAsciiText,
  type AsciiFont,
  type AsciiRenderOptions,
  type AsciiRenderResult,
} from "./asciiTextDrawer.service";
