import type { ComponentType } from "react";

export type ToolIslandModule = { default: ComponentType };
export type ToolLoader = () => Promise<ToolIslandModule>;

/** Lazy loaders for available tool islands — keeps the shell bundle lean. */
export const toolLoaders: Record<string, ToolLoader> = {
  "ascii-text-drawer": () => import("./islands/AsciiTextDrawer"),
  "base-converter": () => import("./islands/BaseConverter"),
  "base64-file-converter": () => import("./islands/Base64FileConverter"),
  "base64-string-converter": () => import("./islands/Base64StringConverter"),
  "basic-auth-generator": () => import("./islands/BasicAuthGenerator"),
  "bcrypt": () => import("./islands/Bcrypt"),
  "benchmark-builder": () => import("./islands/BenchmarkBuilder"),
  "bip39-generator": () => import("./islands/Bip39Generator"),
  "camera-recorder": () => import("./islands/CameraRecorder"),
  "case-converter": () => import("./islands/CaseConverter"),
  "chmod-calculator": () => import("./islands/ChmodCalculator"),
  "chronometer": () => import("./islands/Chronometer"),
  "color-converter": () => import("./islands/ColorConverter"),
  "crontab-generator": () => import("./islands/CrontabGenerator"),
  "date-converter": () => import("./islands/DateConverter"),
  "device-information": () => import("./islands/DeviceInformation"),
  "docker-run-to-docker-compose-converter": () => import("./islands/DockerRunToDockerComposeConverter"),
  "email-normalizer": () => import("./islands/EmailNormalizer"),
  "emoji-picker": () => import("./islands/EmojiPicker"),
  "encryption": () => import("./islands/Encryption"),
  "eta-calculator": () => import("./islands/EtaCalculator"),
  "git-memo": () => import("./islands/GitMemo"),
  "hash-text": () => import("./islands/HashText"),
  "hmac-generator": () => import("./islands/HmacGenerator"),
  "html-entities": () => import("./islands/HtmlEntities"),
  "html-wysiwyg-editor": () => import("./islands/HtmlWysiwygEditor"),
  "http-status-codes": () => import("./islands/HttpStatusCodes"),
  "iban-validator-and-parser": () => import("./islands/IbanValidatorAndParser"),
  "ipv4-address-converter": () => import("./islands/Ipv4AddressConverter"),
  "ipv4-range-expander": () => import("./islands/Ipv4RangeExpander"),
  "ipv4-subnet-calculator": () => import("./islands/Ipv4SubnetCalculator"),
  "ipv6-ula-generator": () => import("./islands/Ipv6UlaGenerator"),
  "json-diff": () => import("./islands/JsonDiff"),
  "json-minify": () => import("./islands/JsonMinify"),
  "json-prettify": () => import("./islands/JsonPrettify"),
  "json-to-csv": () => import("./islands/JsonToCsv"),
  "json-to-toml": () => import("./islands/JsonToToml"),
  "json-to-xml": () => import("./islands/JsonToXml"),
  "json-to-yaml-converter": () => import("./islands/JsonToYamlConverter"),
  "jwt-parser": () => import("./islands/JwtParser"),
  "keycode-info": () => import("./islands/KeycodeInfo"),
  "list-converter": () => import("./islands/ListConverter"),
  "lorem-ipsum-generator": () => import("./islands/LoremIpsumGenerator"),
  "mac-address-generator": () => import("./islands/MacAddressGenerator"),
  "mac-address-lookup": () => import("./islands/MacAddressLookup"),
  "markdown-to-html": () => import("./islands/MarkdownToHtml"),
  "math-evaluator": () => import("./islands/MathEvaluator"),
  "mime-types": () => import("./islands/MimeTypes"),
  "numeronym-generator": () => import("./islands/NumeronymGenerator"),
  "og-meta-generator": () => import("./islands/OgMetaGenerator"),
  "otp-generator": () => import("./islands/OtpGenerator"),
  "password-strength-analyser": () => import("./islands/PasswordStrengthAnalyser"),
  "pdf-signature-checker": () => import("./islands/PdfSignatureChecker"),
  "percentage-calculator": () => import("./islands/PercentageCalculator"),
  "phone-parser-and-formatter": () => import("./islands/PhoneParserAndFormatter"),
  "qrcode-generator": () => import("./islands/QRCodeGenerator"),
  "random-port-generator": () => import("./islands/RandomPortGenerator"),
  "regex-memo": () => import("./islands/RegexMemo"),
  "regex-tester": () => import("./islands/RegexTester"),
  "roman-numeral-converter": () => import("./islands/RomanNumeralConverter"),
  "rsa-key-pair-generator": () => import("./islands/RsaKeyPairGenerator"),
  "safelink-decoder": () => import("./islands/SafelinkDecoder"),
  "slugify-string": () => import("./islands/SlugifyString"),
  "sql-prettify": () => import("./islands/SqlPrettify"),
  "string-obfuscator": () => import("./islands/StringObfuscator"),
  "svg-placeholder-generator": () => import("./islands/SvgPlaceholderGenerator"),
  "temperature-converter": () => import("./islands/TemperatureConverter"),
  "text-diff": () => import("./islands/TextDiff"),
  "text-statistics": () => import("./islands/TextStatistics"),
  "text-to-binary": () => import("./islands/TextToBinary"),
  "text-to-nato-alphabet": () => import("./islands/TextToNatoAlphabet"),
  "text-to-unicode": () => import("./islands/TextToUnicode"),
  "token-generator": () => import("./islands/TokenGenerator"),
  "toml-to-json": () => import("./islands/TomlToJson"),
  "toml-to-yaml": () => import("./islands/TomlToYaml"),
  "ulid-generator": () => import("./islands/UlidGenerator"),
  "url-encoder": () => import("./islands/UrlEncoder"),
  "url-parser": () => import("./islands/UrlParser"),
  "user-agent-parser": () => import("./islands/UserAgentParser"),
  "uuid-generator": () => import("./islands/UuidGenerator"),
  "word-code-generator": () => import("./islands/WordCodeGenerator"),
  "xml-formatter": () => import("./islands/XmlFormatter"),
  "xml-to-json": () => import("./islands/XmlToJson"),
  "yaml-prettify": () => import("./islands/YamlPrettify"),
  "yaml-to-json-converter": () => import("./islands/YamlToJsonConverter"),
  "yaml-to-toml": () => import("./islands/YamlToToml"),
};

export function getToolLoader(slug: string): ToolLoader | undefined {
  return toolLoaders[slug];
}

