export {
  DEFAULT_MAC_CASE,
  DEFAULT_MAC_PREFIX,
  DEFAULT_MAC_SEPARATOR,
  MAC_CASES,
  MAC_QUANTITY_DEFAULT,
  MAC_QUANTITY_MAX,
  MAC_QUANTITY_MIN,
  MAC_SEPARATORS,
  clampMacQuantity,
  generateMacAddresses,
  generateRandomMacAddress,
  isValidPartialMacAddress,
  normalizeMacCase,
  normalizeMacSeparator,
  splitPrefix,
  type GenerateMacAddressesOptions,
  type MacCase,
  type MacSeparator,
} from "./macAddressGenerator.service";
